mod.mc_dep_fabric=>=1.20 <=1.20.1
mod.mc_dep_forgelike=[1.20, 1.20.1]
mod.mc_title=1.20.1
mod.mc_targets=1.20 1.20.1

deps.forge_loader=47.3.0
deps.neoforge_loader=[UNSUPPORTED]

deps.yarn_build=10
deps.cloth_version=11.1.118
deps.jade_version=11.10.0
deps.jade_fabric_version=11.10.0+fabric
deps.wthit_version=8.13.2
deps.badpackets_version=0.4.3
deps.limelight_version=0.1.1+1.21
deps.modmenu_version=7.2.2
deps.owo_version=0.11.2+1.20
deps.useful_spyglass_fabric_version=5245774
deps.useful_spyglass_forge_version=5245771
deps.fabric_api=0.92.3+1.20.1
deps.forge_config_api_port=8.0.1