# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
#org.gradle.parallel=true
org.gradle.caching=true
org.gradle.caching.debug=false
#org.gradle.configureondemand=true

# Mod properties
mod.version=2.1.1
mod.group=cc.cassian
mod.id=item-descriptions
mod.name=Item Descriptions

# Used for the mod metadata
mod.mc_dep_fabric=[VERSIONED]
mod.mc_dep_forgelike=[VERSIONED]
# Used for the release title. I.e. '1.20.x'
mod.mc_title=[VERSIONED]
# Space separated versions for publishing. I.e. '1.20, 1.20.1'
mod.mc_targets=[VERSIONED]

# Mod setup
deps.mixin_extras=0.4.1
deps.fabric_loader=0.16.10
deps.forge_loader=[VERSIONED]
deps.neoforge_loader=[VERSIONED]
deps.neoforge_patch=[VERSIONED]

# Mod dependencies
deps.yarn_build=[VERSIONED]
deps.fabric_api_version=[VERSIONED]
deps.cloth_version=[VERSIONED]
deps.jade_version=[VERSIONED]
deps.jade_fabric_version=[VERSIONED]
deps.wthit_version=[VERSIONED]
deps.badpackets_version=[VERSIONED]
deps.limelight_version=[VERSIONED]
deps.modmenu_version=[VERSIONED]
deps.owo_version=[VERSIONED]
deps.useful_spyglass=[VERSIONED]
deps.useful_spyglass_fabric_version=[VERSIONED]
deps.useful_spyglass_forge_version=[VERSIONED]
deps.forge_config_api_port=[VERSIONED]
deps.fast_item_frames=[VERSIONED]
deps.placeholder_api=[VERSIONED]



# Publishing
publish.modrinth=...
publish.curseforge=...