org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.configuration-cache=true
fabric.loom.dropNonIntermediateRootMethods=true

mod.id=item_descriptions
mod.name=Item Descriptions
mod.group=cc.cassian
mod.version=2.7.8

deps.minecraft=[VERSIONED]
deps.fabric-loader=0.19.2
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.kaleido=0.3.3+1.3.2

publish.modrinth=UaizcMKP
publish.curseforge=1101501
#publish.additionalVersions=