# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.12+1.21.4
maven_group = cc.cassian.item_descriptions
archives_name = item-descriptions
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.4
yarn_mappings = 1.21.4+build.7

# Dependencies - Fabric
fabric_loader_version = 0.16.9
fabric_api_version = 0.114.0+1.21.4
owo_version=0.12.18+1.21.2
limelight_version=0.1.1+1.21
modmenu_version=13.0.0
# Dependencies - NeoForge
neoforge_version = 21.4.50-beta
yarn_mappings_patch_neoforge_version = 1.21+build.4
# Dependencies - Common
cloth_version=17.0.144
jade_version=17.1.2
wthit_version=14.0.1
badpackets_version=0.8.1