mod.mc_dep_fabric=>=1.21.5
mod.mc_dep_forgelike=[1.21.5]
mod.mc_title=1.21.6
mod.mc_targets=1.21.6 1.21.7

deps.forge_loader=[UNSUPPORTED]
deps.neoforge_loader=21.5.6-beta
deps.neoforge_patch=1.21+build.4

deps.yarn_build=2
deps.cloth_version=18.0.145
deps.jade_version=18.0.1+neoforge
deps.jade_fabric_version=18.0.1+fabric
deps.wthit_version=14.0.1
deps.badpackets_version=0.8.1
deps.limelight_version=0.1.1+1.21
deps.modmenu_version=14.0.0-rc.2
deps.owo_version=0.12.15+1.21
deps.useful_spyglass=0.7.0
deps.fabric_api=0.123.1+1.21.6
deps.forge_config_api_port=21.5.1
deps.fast_item_frames=GVMdKuJR
deps.puzzles_lib=V4N99PoP
deps.glowcase=1.9.0+1.21
deps.placeholder_api=2.5.2+1.21.3
deps.polymer=0.12.1+1.21.5-rc2
