mod.mc_dep_fabric=>=1.21.4
mod.mc_dep_forgelike=[1.21.4]
mod.mc_title=1.21.4
mod.mc_targets=1.21.4 25w02a

deps.forge_loader=[UNSUPPORTED]
deps.neoforge_loader=21.4.54-beta
deps.neoforge_patch=1.21+build.4

deps.yarn_build=8
deps.cloth_version=17.0.144
deps.jade_version=17.1.2
deps.jade_fabric_version=17.1.2+fabric
deps.wthit_version=14.0.1
deps.badpackets_version=0.8.1
deps.limelight_version=0.1.1+1.21
deps.modmenu_version=13.0.0
deps.owo_version=0.12.15+1.21
deps.useful_spyglass_fabric_version=5934246
deps.useful_spyglass_forge_version=5934235
deps.fabric_api=0.114.0+1.21.4
deps.forge_config_api_port=21.4.1