mod.mc_dep_fabric=>=1.21.9
deps.minecraft=1.21.10
publish.additionalVersions=1.21.9

deps.parchment=1.21.9:2025.10.05

deps.cloth_version=20.0.148
deps.jade=20.0.2+fabric
deps.wthit_version=17.0.4
deps.fabric_api=0.134.1+1.21.10
deps.glowcase=2.3.0+1.21
deps.placeholder_api=2.7.1+1.21.6
deps.polymer=0.14.2+1.21.9
deps.yacl=3.8.0+1.21.9
deps.modmenu_version=16.0.0-rc.1