mod.mc_dep_forge=26.1, 26.2
deps.minecraft=26.1.2
mod.mc_targets=26.1.2
publish.curseforge_minecraft_version=26.1.2
publish.additionalVersions=26.1,26.1.1

deps.neoforge=26.1.2.103

deps.wthit=19.0.1
deps.cloth=26.1.154
deps.badpackets=neo-0.12.2
deps.fast_item_frames=5QiStm7o
deps.puzzles_lib=24CC3oNl