mod.mc_dep_fabric=>=1.21.6 <1.21.9
deps.minecraft=1.21.8
publish.additionalVersions=1.21.7

deps.parchment=1.21.8:2025.09.14

deps.cloth_version=19.0.147
deps.jade=19.3.2+fabric
deps.wthit_version=16.0.1
deps.badpackets_version=0.9.0
deps.limelight_version=0.1.1+1.21
deps.modmenu_version=15.0.0-beta.3
deps.owo_version=0.12.21+1.21.6
deps.fabric_api=0.136.1+1.21.8
deps.forge_config_api_port=21.8.1
deps.fast_item_frames=7Km4n5kj
deps.puzzles_lib=sYuwlGfN
deps.glowcase=2.3.4+1.21.7
deps.placeholder_api=2.7.1+1.21.6
deps.polymer=0.13.13+1.21.8
deps.yacl=3.7.1+1.21.6