architectury {
    common rootProject.enabled_platforms.split(',')
}


repositories {
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
}


dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modApi "me.shedaniel.cloth:cloth-config:${project.cloth_version}"
    modImplementation "maven.modrinth:jade:${project.jade_version}+fabric"
    modCompileOnly "mcp.mobius.waila:wthit-api:fabric-${project.wthit_version}"
    // Useful Spyglass
    modCompileOnly("curse.maven:useful-spyglass-840027:5934246")
}
