modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "item_descriptions"
version = "${version}"
displayName = "Item Descriptions"
authors = "cassiancc"
description = '''
This mod adds unique descriptions for all blocks, items, and mobs - built in a way that makes it easy to add modded content.
'''
logoFile = "assets/item_descriptions/icon.png"
issueTrackerURL = "https://github.com/cassiancc/Item-Descriptions/issues"
displayURL="https://github.com/cassiancc/Item-Descriptions/wiki"
modURL="https://github.com/cassiancc/Item-Descriptions/wiki"


[[dependencies.item_descriptions]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.item_descriptions]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"