mod.mc_dep_forge=1.21.9, 1.21.10
deps.minecraft=1.21.10
mod.mc_targets=1.21.10
publish.additionalVersions=1.21.9
publish.curseforge_minecraft_version=1.21.11

deps.neoforge=21.10.64
deps.parchment=1.21.10:2025.10.12

deps.jade=20.0.5+neoforge
deps.wthit_version=17.0.4
deps.cloth_version=20.0.148
deps.yacl=3.8.0+1.21.9
