mod.mc_dep_fabric=>=1.21 <=1.21.1
mod.mc_dep_forgelike=[1.21, 1.21.1]
mod.mc_title=1.21.1
mod.mc_targets=1.21 1.21.1

deps.forge_loader=[UNSUPPORTED]
deps.neoforge_loader=21.1.77
deps.neoforge_patch=1.21+build.4

deps.yarn_build=3
deps.cloth_version=15.0.127
deps.jade_version=15.1.3+neoforge
deps.jade_fabric_version=15.1.3+fabric
deps.wthit_version=12.2.2
deps.badpackets_version=0.8.1
deps.limelight_version=0.1.1+1.21
deps.modmenu_version=11.0.1
deps.owo_version=0.12.15+1.21
deps.useful_spyglass_fabric_version=5934246
deps.useful_spyglass_forge_version=5934235
deps.fabric_api=0.114.0+1.21.1
deps.forge_config_api_port=21.1.3