mod.mc_dep_forgelike=[1.20, 1.20.1]
deps.minecraft=1.20.1
mod.mc_targets=1.20 1.20.1

deps.forge=1.20.1-47.4.0
deps.parchment=1.20.1:2023.09.03

deps.cloth_version=11.1.118
deps.jade=11.13.2+forge
deps.wthit_version=8.13.2
deps.badpackets_version=0.4.3
deps.limelight_version=0.1.1+1.21
deps.modmenu_version=7.2.2
deps.owo_version=0.11.2+1.20
deps.useful_spyglass=0.8.0-forge
deps.fast_item_frames=vmfgQQur
deps.puzzles_lib=6dQXvzl5
deps.glowcase=SDmym7mA
deps.placeholder_api=2.1.4+1.20.1
deps.yacl=3.6.6+1.20.1