mod.mc_dep_fabric=>=1.20 <=1.20.1
mod.mc_dep_forgelike=[1.20, 1.20.1]
deps.minecraft=1.20.1
mod.mc_targets=1.20 1.20.1

deps.forge_loader=47.3.0
deps.neoforge_loader=[UNSUPPORTED]
deps.parchment=1.20.1:2023.09.03

deps.yarn_build=10
deps.cloth_version=11.1.118
deps.jade=11.10.0+fabric
deps.wthit_version=8.13.2
deps.badpackets_version=0.4.3
deps.limelight_version=0.1.1+1.21
deps.modmenu_version=7.2.2
deps.owo_version=0.11.2+1.20
deps.useful_spyglass=0.6.1
deps.fabric_api=0.92.3+1.20.1
deps.forge_config_api_port=8.0.1
deps.fast_item_frames=vmfgQQur
deps.puzzles_lib=6dQXvzl5
deps.glowcase=SDmym7mA
deps.placeholder_api=2.1.4+1.20.1
deps.yacl=3.6.6+1.20.1