mod.mc_dep_fabric=>=26.1 <26.2
deps.minecraft=26.1.2
publish.curseforge_minecraft_version=26.1.2
publish.additionalVersions=26.1,26.1.1

deps.cloth=26.1.154
deps.wthit=19.0.1
deps.fabric_api=0.151.0+26.1.2
deps.placeholder_api=2.7.1+1.21.6
deps.polymer=0.16.1+26.1.1
deps.modmenu=18.0.0-alpha.8
deps.jade=26.0.2+fabric
deps.yacl=3.9.0+26.1
deps.badpackets=fabric-0.12.2
deps.puzzles_lib=3OADGa7L
deps.forge_config_api_port=26.1.4